name: CI Build

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: make image

      - name: Push image
        if: ${{ github.ref_name == 'master' }}
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        run: make push-to-ghcr
